#!name=哔哩哔哩签到
#!desc=在APP里观看番剧即可获取Cookie,获取完Cookie请自行禁用获取脚本
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/bilibili_4.png

[Script]

# > 哔哩哔哩签到
http-request ^https:\/\/(www|live)\.bilibili\.com\/?.? script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.cookie.js, tag=哔哩哔哩Cookie获取
cron "10 0 0 * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.js, tag=哔哩哔哩签到

hostname = *.bilibili.com
