# 获取Cookie订阅
# 该订阅仅适用于定时签到脚本的Cookie获取.
# 您可以在使用后手动将其禁用，以免产生不必要的MITM.

# Chavy  

# > ZhiYi-N
http-request https:\/\/veishop\.iboxpay\.com\/nf_gateway\/nf_customer_activity\/day_cash\/v1\/give_gold_coin_by_video\.json script-path=https://raw.githubusercontent.com/ZhiYi-N/Private-Script/master/Scripts/xp.js, requires-body=true, timeout=10, tag=笑谱

hostname = veishop.iboxpay.com
