#!name=网易云音乐签到
#!desc=配合BoxJs配置取货地区及需求产品
#!author=Cookie获取点击登陆
#!homepage=https://music.163.com/m/login
#!author=再点击
#!homepage=https://music.163.com/#/user/level
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netease_Music.png

[Script]

# > 网易云音乐签到
http-request ^https:\/\/music.163.com\/weapi\/user\/level script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.cookie.js,requires-body=true, tag=网易云Cookie获取
cron "10 0 0 * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.js, tag=网易云签到

hostname = music.163.com
